#!/usr/bin/env bash

PID=0

init() {
  killall tunvis > /dev/null 2>&1
#   # EXTRA CHECK
#   # iptables -I INPUT -i enp0s3 -j DROP
#   echo -n ""
}

destroy() {
  kill $PID
  killall tunvis > /dev/null 2>&1
}

trap ctrl_c INT
ctrl_c() {
    echo "rtunvis: Trapped CTRL-C"
    destroy
    exit
}

while true; do
  init
  ./tunvis &
  PID=$!
  inotifywait ./tunvis
  destroy
  sleep 1
done
