#!/usr/bin/env bash

PID=0

destroy() {
    kill $PID
    killall tunvis

    iptables -t mangle -D PREROUTING -i tun12 -j MARK --set-mark 42
    iptables -t nat -D POSTROUTING -j SNAT --to-source 192.168.101.137
    ip route del table TUNVIS default via 192.168.101.1
    ip rule del fwmark 42 table TUNVIS
}

trap ctrl_c INT
ctrl_c() {
    echo "** Trapped CTRL-C"
    destroy
    exit
}

killall tunvis

while true; do
  ./tunvis &
  PID=$!
  inotifywait ./tunvis
  destroy
  sleep 2
done
