#!/usr/bin/env bash

PID=0

trap ctrl_c INT
ctrl_c() {
    echo "** Trapped CTRL-C"
    kill $PID
    killall tunvis
    ip route del table TUNVIS default via 192.168.101.1
    ip rule del fwmark 42 table TUNVIS
    exit
}

killall tunvis

while true; do
  ./tunvis &
  PID=$!
  inotifywait ./tunvis
  kill $PID
  killall tunvis
  ip route del table TUNVIS default via 192.168.101.1
  ip rule del fwmark 42 table TUNVIS
  sleep 2
done
